-- ids de tabelas e campos especificos censurados


WITH insumo_original AS (
SELECT DISTINCT
    DSC_CLASSE_TERAPEUTICA__c, -- possivelmente inutil já que a classificação é feita em cima da principio ativo 
    COD_TUSS_CONSOLIDADO__c, -- codigo_tuss (outra observação é que na tabela original existem outras colunas com codigo tuss)
    DSC_PRINCIPIO_ATIVO__c, --principio ativo que vou classificar
    DSC_MEDICAMENTO_REF__c --marca talvez eu comente
FROM tab
WHERE 1=1
  AND FRM_TIPO_REGISTRO__c = 'Medicamento'
  AND CODIGO_SAS__C IS NULL
),
-- Nova CTE para normalizar o princípio ativo da insumo_original
insumo_com_pa_normalizado AS (
SELECT
    iou.DSC_CLASSE_TERAPEUTICA__c,
    iou.COD_TUSS_CONSOLIDADO__c,
    iou.DSC_PRINCIPIO_ATIVO__c AS INS_PRINCIPIO_ATIVO_ORIGINAL,
    CASE 
        WHEN UPPER(iou.DSC_PRINCIPIO_ATIVO__c) = 'RUXIENCE' THEN 'RITUXIMABE'
        WHEN UPPER(iou.DSC_PRINCIPIO_ATIVO__c) = 'IMUNOGLOBULINA G' THEN 'IMUNOGLOBULINA HUMANA'
        ELSE iou.DSC_PRINCIPIO_ATIVO__c 
    END AS INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
    iou.DSC_MEDICAMENTO_REF__c
FROM tab iou
),
-- Sua CTE de classificação final
nao_espec_classificacao_final AS (
SELECT
    ipan.DSC_CLASSE_TERAPEUTICA__c AS INS_DSC_CLASSE_TERAPEUTICA_ORIG,
    ipan.COD_TUSS_CONSOLIDADO__c,
    ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
    ipan.DSC_MEDICAMENTO_REF__c AS INS_DSC_MEDICAMENTO_REF,
    CASE -- Lógica de DSC_CLASSIFICACAO_MEDICAMENTO_NOVA da tb_class_med_final, aplicada ao INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ABATACEPTE','ACTEMRA','ADALIMUMABE','ADCETRIS','AMGEVITA','ATEZOLIZUMABE','AVASTIN','AVELUMABE','AVONEX','AVSOLA','BACILLUS CALMETTE GUERIN LIOFILIZADO','BAVENCIO','BENLYSTA','BESPONSA','BEVACIZUMABE','BIO MANGUINHOS INFLIXIMABE','BLAUIMUNO','BLINATUMOMABE','BLINCYTO','BLYNCITO','BRENTUXIMABE','BRENZYS','CEMIPLIMABE','CETUXIMABE','CIMZIA','COSENTYX','CUVITRU','CYRAMZA','DALINVI','DARATUMUMABE','DUPIXENT','DURVALUMABE','ELOVIE','EMPLICITI','ENBREL','ENBREL PFS','ENDOBULIN KIOVIG','ENDOBULIN KIOVIG','ENHERTU','ENTYVIO','ERBITUX','ERELZI','EVUSHELD','FASENRA','FLEBOGAMMA','GAMUNEX','GAMUNEX','GAZYVA','HERCEPTIN','HERZUMA','HIZENTRA','HUMIRA','HYQVIA','HYQVIA','HYRIMOZ','IDACIO','ILARIS','IMFINZI','IMJUDO','IMUNO BCG','IMUNOGLOBULIN','IMUNOGLOBULIN','INFLIXIMABE','INTRATECT','IPILIMUMABE','ISATUXIMABE','JEMPERLI','KADCYLA','KANJINTI','KESIMPTA','KEYTRUDA','LARTRUVO','LEMTRADA','LIBTAYO','MABTHERA','MABTHERA','MABTHERA','MEPACT','MEPOLIZUMABE','MYCOBACTERIUM BOVIS','MYLOTARG','NIVOLUMABE','NUCALA','OBINUTUZUMABE','OCREVUS','OCTAGAM','OFATUMUMABE','ONCO BCG','OPDIVO','ORENCIA','PANITUMUMABE','PEMBROLIZUMABE','PENTAGLOBIN','PERJETA','PERTUZUMABE','PHESGO','ROPOLIVY','QARZIBA','REBIF','REMICADE','REMSIMA','RITUXIMABE','RITUXIMABE','RIXIMYO','RIXIMYO','RIXIMYO','RUXIENCE','RYBREVANT','SANDOGLOBULINA','SARCLISA','SECUQUINUMABE','SIMPONI','SKYRIZI','STELARA','TALTZ','TECENTRIQ','TECVAYLI','TEGELINE','TRASTUZUMABE','TRASTUZUMABE DERUXTECANO','TRASTUZUMABE ENTANSINA','TRAZIMERA','TREMFYA','TRODELVY','TRUXIMA','TRUXIMA','TYSABRI','UNITUXIN','UROHIPE BCG','USTEQUINUMABE','VACINA BCG','VECTIBIX','VEDOLIZUMABE','VIVAXXIA','VIVAXXIA','XILBRILADA','XILFYA','XOLAIR','YERVOY','ZEDORA') THEN 'IMUNOTERAPIA - IMUNOBIOLOGICO'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('IMNOVID','LENALIDOMIDA','NUVYOR','POMALID','POMALYST','REVLIMID') THEN 'IMUNOTERAPIA - NAO IMUNOBIOLOGICO'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ACIDO ZOLEDRONICO','ACLASTA','AKYNZEO','ALFAEPOETINA','ARANESP','AREDIA','BLAZTERE','CUPRIMINE','DENOSUMABE','EPREX','ERITROMAX','ERITROPOETINA','FAULDLEUCO','FAULDPAMI','HEMAX','NETUPITANTO','ONTRAX','PROLIA','REUQUINOL','TECNOCARB','TEORO','TEPADINA','XGEVA','ZOLIBBS','ZOMETA') THEN 'MEDICAMENTO DE SUPORTE'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('FILGRASTIM','FILGRASTINE','FIPRIMA','FULPHILA','GRANULOKINE','LEUKINE','LIPEGFILGRASTIM','LONQUEX','NEULASTIM','PEGFILGRASTIM','PELGRAZ','TEVAGRASTIM','ZARZIO') THEN 'MEDICAMENTO DE SUPORTE IMUNOBIOLOGICO'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ABRAXANE','ACIDO TRANSRETINOICO','ADRIAMICINA','ADRIBLASTINA','ALIMTA','ALKERAN','ARACYTIN','ASPARAGINASE','ATRED','AZACITIDINA','B - PLATIN','BECENUN','BENALQ','BENDAMUSTINA','BICNU','BIOEZULEN','BLENOXANE','BLEOCEL','BLEOCINS','BLEOMICINA','BLEOMYCIN','BONAR','BRECILA','BUCELON','BUSILVEX','BUSSULFANO','BUSULFEX','C - PLATIN','CAAB','CABAZITAXEL','CABAZRED','CAELYX','CAMPTOSAR','CAPECITABINA','CARBOPLATINA','CARMUSTINA','CICLOFOSFAMIDA','CISPLATEX','CISPLATINA','CITARABINA','CITARAX','CITOPLAX','CITOSTAL','CLORITECAN','COLLECTRO','CORRETAL','COSMEGEN','DACARB','DACARBAZINA','DACILON','DACOGEN','DACTINOMICINA','DAUNOBLASTINA','DAUNOCIN','DAUNORRUB','DAUNORRUBICINA','DECITABINA','DETIMEDAC','DOCELIBBS','DOCETAXEL','DOCEUNO','DOCKS','DOXOLEN','DOXOPEG','DOXORRUBICINA','ELOXATIN','EPIRRUBICINA','EPOSIDO','EROXYM','ERWINASE','ETOPOSIDEO','ETOPOSIDO','EUNADES','EVOCLASS','EVODAZIN','EVOFLUBINA','EVOLOX','EVOMID','EVOMIXAN','EVOPOSDO','EVORUBICIN','EVOTABINA','EVOTAXEL','EVOTERIN','EVOXALI','EVOZAR','EZULEN','FARMORUBICINA','FAULBLASTINA','FAULDACAR','FAULDCARBO','FAULDCISPLA','FAULDCITA','FAULDFLUOR','FAULDMETRO','FAULDOXO','FAULDVINCRI','FLUDALIBBS','FLUDARA','FLUDARABINA','FLUORURACILA','FLUSAN','GCIB','GEMCIT','GEMZAR','GENABYX','GENCITABINA','GENCIX','GENLIBBS','GENUXAL','HIDROXIUREIA','HOLOXANE','HYCAMTIN','HYDREA','HYTAS','IDA','IDARRUBICINA','IFOSFAMIDA','IRINOTECANO','IRNOCAM','IRO','JAVLOR','JEVTANA','LANVIS','LEUKERAN','LEUSTATIN','LEUX','LEVACT','LIFOS','LISODREN','LONSURF','MELFALANO','MELPHALAN','MERCAPTOPURINA','MESOTEM','METOTREXATO','METREXATO','MIANTREX','MITOCIN','MITOMICINA','MITOXANTRONA','MTX','MUPHORAN','NATULAN','NAVELBINE','NEOCITEC','NIBISNU','NORELBIN','ONCASPAR','ONCODOCEL','ONCODOX','ONCOVIN','ONIVYDE','ONTAX','OPLAT','OXA','OXALIBBS','OXALIMEIZ','OXALIPLATINA','PACLITAX','PACLITAXEL','PARAPLATIN','PAREXEL','PEGASPARGASE','PEMEGLENN','PEMETREXEDE','PEMTRYX','PLATAMINE','PLATISTINE','PLEXEDEN','PROAZITAX','PROCARBAZINA','PROTOITECAN','PURINETHOL','RABINEFIL','REDTIBIN','RIBOMUSTIN','RUBIDOX','SPECTRILA','SUKHI','TACE','TARVEXOL','TAXILAN','TAXOL','TAXOTERE','TECNOCRIS','TECNOMICINA','TECNOTECAN','TEMODAL','TEMOLIDA','TEMOZOLOMIDA','TEPEV','TEVACARBO','TEVAETOPO','TEVAMETHO','TEVAOXALI','TIOTEPA','TOPORAN','TOPOTECANA','TREBYXAN','TRETINOINA','TRIOXIDO DE ARSENIO','TRISENOX','VANCEL','VELBAN','VEPESID','VESANOID','VIDAZA','VILNE','VIMBLASTINA','VINCIZINA','VINCRISTINA','VINORELBINA','WINDUZA','XELODA','YONDELIS','ZAVEDOS') THEN 'QUIMIOTERAPICO'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('AFINITOR','ALECENSA','ALUNBRIG','BELEODAQ','BORTEZOMIBE','BOZORED','BRAFTOVI','BRUKINSA','CABOMETYX','CALQUENCE','CAPRELSA','CARBOMETYX','CARFILZOMIBE','CERTICAN','COTELLIC','ELOME','ERFANDEL','ERIBULINA','ERIVEDGE','EVEROLIMO','EVOBRIG','FYARRO','GIOTRIF','GLIMATIN','GLIVEC','HALAVEN','IBRANCE','ICLUSIG','IMATINIBE','IMBRUVICA','INLYTA','IRESSA','JAKAVI','KISQALI','KOSELUGO','KYPROLIS','LENVATINIBE','LENVIMA','LEUPHILA','LORBRENA','LORVIQUA','LUMAKRAS','LYNPARZA','MEKINIST','MEKTOVI','MIELOCADE','NERLYNX','NEXAVAR','NINLARO','NINTEDANIBE','OFEV','OLAPARIBE','OLUMIANT','PAZOPANIBE','PIQRAY','RETEVMO','RINVOQ','RYDAPT','SPRYCEL','STIVARGA','SUTENT','TABRECTA','TAFINLAR','TAGRISSO','TARCEVA','TASIGNA','TEPMETKO','TIBSOVO','TORISEL','TOVAR','TRAMETINIBE','TYKERB','VELCADE','VENCLEXTA','VENETOCLAX','VERAZO','VERZENIOS','VITRAKVI','VOTRIENT','WELIREG','XALKORI','XELJANZ','XOSPATA','ZALTRAP','ZEJULA','ZELBORAF','ZOMI','ZYKADIA') THEN 'TERAPIA ALVO - DROGAS SINTETICAS'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ABIRATERONA','ANASTROLIBBS','ANASTROZOL','ARAZABI','ARIMIDEX','AROMASIN','BICALUTAMIDA','CASODEX','CINACALCETE','DEGARELIX','DESTILBENOL','ELIGARD','ERLEADA','EXEMESTANO','FASLODEX','FEMARA','FEMIGESTROL','FIRMAGON','FULVESTRANTO','GOSSERRELINA','LANREOTIDA','LECTRUM','LETROZOL','LEUPRORRELINA','LUPRON DEPOT','MATIZ','MEGESTAT','NEO DECAPEPTYL','NOLVADEX D','NUBEQA','OCTREOTIDA','OCTRIDE','POEMMY','PROEXTY','RARIJA','SANDOSTATIN','SELETIV','SOMATULINE','SUPRENIQ','TACFEN','TAMOXIFENO','TAMOXIM','TAXOFEN','TECNOTAX','TRIPTORRELINA','VEQUILE','XTANDI','ZOLADEX','ZOSTIDE','ZYTIGA') THEN 'TERAPIA ENDOCRINA'
        ELSE 'REVER'
    END AS INS_DSC_CLASSIFICACAO_MEDICAMENTO_NOVA,

    CASE -- Lógica de DSC_CLASSIFICACAO_VIA_ACESSO_NOVA da tb_class_med_final, aplicada ao INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('TECNOCARB','TEPADINA','LEVACT','RIBOMUSTIN','BENDAMUSTINA','BUSILVEX','BUSULFEX','BUSSULFANO','BUCELON','VANCEL','BICNU','BECENUN','NIBISNU','CARMUSTINA','DACARB','EVODAZIN','DETIMEDAC','FAULDACAR','DACARBAZINA','MUPHORAN','LIFOS','EVOLOX','HOLOXANE','IFOSFAMIDA','TEMOLIDA','TIOTEPA','CITARAX','FAULDCITA','CITARABINA','DACOGEN','REDTIBIN','DECITABINA','FLUDARA','EVOFLUBINA','FLUDALIBBS','FLUDARABINA','FLUSAN','FAULDFLUOR','FLUORURACILA','GCIB','EVOZAR','GEMCIT','GEMZAR','GENCIX','GENABYX','GENLIBBS','GENCITABINA','ATRED','SUKHI','ALIMTA','EROXYM','MESOTEM','PEMTRYX','PLEXEDEN','PEMEGLENN','PEMETREXEDE','YONDELIS','VELBAN','RABINEFIL','VIMBLASTINA','FAULBLASTINA','ONCOVIN','TECNOCRIS','VINCIZINA','FAULDVINCRI','VINCRISTINA','JAVLOR','VILNE','NEOCITEC','NORELBIN','EVOTABINA','NAVELBINE','VINORELBINA','TACE','DOCEUNO','TAXOTERE','DOCELIBBS','DOCETAXEL','ONCODOCEL','ONTAX','TAXOL','PAREXEL','TAXILAN','EVOTAXEL','PACLITAX','TARVEXOL','PACLITAXEL','ABRAXANE','CABAZRED','PROAZITAX','CABAZITAXEL','CAAB','JEVTANA','IRO','IRNOCAM','ONIVYDE','EVOTERIN','TREBYXAN','CAMPTOSAR','CLORITECAN','TECNOTECAN','IRINOTECANO','PROTOITECAN','TOPORAN','HYCAMTIN','TOPOTECANA','TEVAETOPO','BONAR','BLEOCEL','BLEOCINS','BLENOXANE','BLEOMYCIN','BLEOMICINA','TECNOMICINA','IDA','DACILON','COSMEGEN','DACTINOMICINA','DAUNOCIN','EVOCLASS','DAUNORRUB','DAUNOBLASTINA','DAUNORRUBICINA','DOCKS','DOXOLEN','ONCODOX','RUBIDOX','FAULDOXO','EVORUBICIN','ADRIAMICINA','ADRIBLASTINA','DOXORRUBICINA','CAELYX','DOXOPEG','BRECila','EPIRRUBICINA','FARMORUBICINA','EVOMID','ZAVEDOS','IDARRUBICINA','MITOCIN','MITOMICINA','EVOMIXAN','MITOXANTRONA','TORISEL','CARBOMETYX','LARTRUVO','EMPLICITI','GAZYVA','OBINUTUZUMABE','ELOVIE','AVASTIN','BEVACIZUMABE','PERJETA','PERTUZUMABE','ZEDORA','HERZUMA','KANJINTI','HERCEPTIN','TRAZIMERA','TRASTUZUMABE','TRASTUZUMABE DERUXTECANO','TRASTUZUMABE ENTANSINA','ENHERTU','KADCYLA','ERBITUX','CETUXIMABE','VECTIBIX','PANITUMUMABE','TECENTRIQ','ATEZOLIZUMABE','BAVENCIO','AVELUMABE','LIBTAYO','CEMIPLIMABE','JEMPERLI','IMFINZI','DURVALUMABE','OPDIVO','NIVOLUMABE','KEYTRUDA','PEMBROLIZUMABE','RYBREVANT','QARZIBA','BLINCYTO','BLYNCITO','BLINATUMOMABE','ADCETRIS','BRENTUXIMABE','DALINVI','DARATUMUMABE','UNITUXIN','MYLOTARG','TRODELVY','BESPONSA','SARCLISA','ISATUXIMABE','ROPOLIVY','TECVAYLI','TRUXIMA','MABTHERA','VIVAXXIA','RITUXIMABE','CYRAMZA','YERVOY','IPILIMUMABE','IMJUDO','PLATAMINE','TEVACARBO','B - PLATIN','FAULDCARBO','PARAPLATIN','CARBOPLATINA','CITOPLAX','CISPLATEX','C - PLATIN','CISPLATINA','PLATISTINE','FAULDCISPLA','OXA','OPLAT','EZULEN','EVOXALI','ELOXATIN','OXALIBBS','COLLECTRO','OXALIMEIZ','TEVAOXALI','OXALIPLATINA','KYPROLIS','CARFILZOMIBE','BELEODAQ','SPECTRILA','ASPARAGINASE','PEGASPARGASE','TRISENOX','TRIOXIDO DE ARSENIO','MEPACT','ERWINASE','HALAVEN','ERIBULINA','AREDIA','FAULDPAMI','TEORO','ZOMETA','ACLASTA','ZOLIBBS','BLAZTERE','ACIDO ZOLEDRONICO','LEUSTATIN','OFATUMUMABE','ZALTRAP','FAULDLEUCO') THEN 'EV'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ONCASPAR') THEN 'EV / IM'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('EPREX','HEMAX','ERITROMAX','ARANESP','OCTRIDE','OCTREOTIDA','SANDOSTATIN','VIDAZA','WINDUZA','AZACITIDINA','ZOMI','ELOME','TOVAR','VERAZO','BOZORED','VELCADE','MIELOCADE','BORTEZOMIBE','LEUKINE','FIPRIMA','FILGRASTIM','FILGRASTINE','GRANULOKINE','ARAZABI') THEN 'EV / SC'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ARACYTIN') THEN 'EV / SC / IT'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ELIGARD','LECTRUM','LUPRON DEPOT','LEUPRORRELINA') THEN 'IM / SC'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('TRIPTORRELINA','NEO DECAPEPTYL','ONCO BCG','IMUNO BCG','VACINA BCG','UROHIPE BCG','MYCOBACTERIUM BOVIS','POEMMY','SELETIV','FASLODEX','SUPRENIQ','FULVESTRANTO') THEN 'IM'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('BACILLUS CALMETTE GUERIN LIOFILIZADO') THEN 'INTRAVESICAL'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ONTRAX','GENUXAL','CICLOFOSFAMIDA','ALKERAN','MELFALANO','MELPHALAN','TEMODAL','TEMOZOLOMIDA','MTX','HYTAS','MIANTREX','METREXATO','TEVAMETHO','FAULDMETRO','METOTREXATO','EPOSIDO','EUNADES','EVOPOSDO','ETOPOSIDO','ETOPOSIDEO') THEN 'EV / VO'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('AKYNZEO','NETUPITANTO','CINACALCETE','BENALQ','LEUKERAN','CITOSTAL','CAPECITABINA','PURINETHOL','MERCAPTOPURINA','LANVIS','LONSURF','XELODA','CORRETAL','VEPESID','CABOMETYX','ZYKADIA','VERZENIOS','SPRYCEL','GLIVEC','GLIMATIN','LEUPHILA','IMATINIBE','TASIGNA','ICLUSIG','GIOTRIF','ALECENSA','WELIREG','TARCEVA','IRESSA','TAGRISSO','ALUNBRIG','EVOBRIG','XALKORI','LORBRENA','LORVIQUA','MEKTOVI','COTELLIC','TAFINLAR','MEKINIST','TRAMETINIBE','BRAFTOVI','KOSELUGO','ZELBORAF','IBRANCE','KISQALI','CALQUENCE','IMBRUVICA','TABRECTA','PIQRAY','INLYTA','ERFANDEL','TYKERB','VITRAKVI','LENVIMA','LENVATINIBE','RYDAPT','NERLYNX','VOTRIENT','PAZOPANIBE','STIVARGA','JAKAVI','RETEVMO','NEXAVAR','SUTENT','TEPMETKO','CAPRELSA','BRUKINSA','XOSPATA','BIOEZULEN','TRETINOINA','ACIDO TRANSRETINOICO','VESANOID','NINLARO','ERIVEDGE','ZEJULA','LYNPARZA','OLAPARIBE','LEUX','TEPEV','HYDREA','HIDROXIUREIA','LISODREN','DESTILBENOL','MEGESTAT','FEMIGESTROL','NUVYOR','REVLIMID','LENALIDOMIDA','IMNOVID','POMALID','POMALYST','NATULAN','PROCARBAZINA','VENCLEXTA','VENETOCLAX','TIBSOVO','LUMAKRAS','TACFEN','TAMOXIM','TAXOFEN','TECNOTAX','NOLVADEX D','TAMOXIFENO','MATIZ','RARIJA','ZYTIGA','ZOSTIDE','ABIRATERONA','ERLEADA','CASODEX','BICALUTAMIDA','NUBEQA','XTANDI','ARIMIDEX','ANASTROZOL','ANASTROLIBBS','PROEXTY','AROMASIN','EXEMESTANO','FEMARA','LETROZOL','VEQUILE','AFINITOR','CERTICAN','EVEROLIMO','FYARRO','OFEV','NINTEDANIBE') THEN 'VO'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('ALFAEPOETINA','ERITROPOETINA','LANREOTIDA','SOMATULINE','PHESGO','RIXIMYO','RIXIMYO','RUXIENCE','ZOLADEX','GOSSERRELINA','ZARZIO','TEVAGRASTIM','LONQUEX','LIPEGFILGRASTIM','PELGRAZ','FULPHILA','NEULASTIM','PEGFILGRASTIM','FIRMAGON','DEGARELIX','XGEVA','PROLIA','DENOSUMABE','KESIMPTA') THEN 'SC'
        ELSE 'NAO SE APLICA'
    END AS INS_DSC_CLASSIFICACAO_VIA_ACESSO_NOVA,

    CASE -- Lógica de ESPECIALIDADE_PRIMARIA da tb_class_med_final, aplicada ao INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('EPREX','HEMAX','ERITROMAX','ARANESP','ALFAEPOETINA','ERITROPOETina','LANREOTIDA','SOMATULINE','OCTRIDE','OCTREOTIDA','SANDOSTATIN','CINACALCETE','BENALQ','LEVACT','RIBOMUSTIN','BENDAMUSTINA','BUSILVEX','BUSULFEX','BUSSULFANO','BUCELON','VANCEL','BICNU','BECENUN','NIBISNU','CARMUSTINA','GENUXAL','CICLOFOSFAMIDA','LEUKERAN','DACARB','EVODAZIN','DETIMEDAC','FAULDACAR','DACARBAZINA','MUPHORAN','LIFOS','EVOLOX','HOLOXANE','IFOSFAMIDA','CITOSTAL','ALKERAN','MELFALANO','MELPHALAN','TEMODAL','TEMOLIDA','TEMOZOLOMIDA','TIOTEPA','CAPECITABINA','VIDAZA','WINDUZA','AZACITIDINA','CITARAX','ARACYTIN','FAULDCITA','CITARABINA','DACOGEN','REDTIBIN','DECITABINA','FLUDARA','EVOFLUBINA','FLUDALIBBS','FLUDARABINA','FLUSAN','FAULDFLUOR','FLUORURACILA','GCIB','EVOZAR','GEMCIT','GEMZAR','GENCIX','GENABYX','GENLIBBS','GENCITABINA','PURINETHOL','MERCAPTOPURINA','MTX','HYTAS','MIANTREX','METREXATO','TEVAMETHO','FAULDMETRO','METOTREXATO','ATRED','SUKHI','ALIMTA','EROXYM','MESOTEM','PEMTRYX','PLEXEDEN','PEMEGLENN','PEMETREXEDE','LANVIS','LONSURF','XELODA','CORRETAL','YONDELIS','VELBAN','RABINEFIL','VIMBLASTINA','FAULBLASTINA','ONCOVIN','TECNOCRIS','VINCIZINA','FAULDVINCRI','VINCRISTINA','JAVLOR','VILNE','NEOCITEC','NORELBIN','EVOTABINA','NAVELBINE','VINORELBINA','TACE','DOCEUNO','TAXOTERE','DOCELIBBS','DOCETAXEL','ONCODOCEL','ONTAX','TAXOL','PAREXEL','TAXILAN','EVOTAXEL','PACLITAX','TARVEXOL','PACLITAXEL','ABRAXANE','CABAZRED','PROAZITAX','CABAZITAXEL','CAAB','JEVTANA','IRO','IRNOCAM','ONIVYDE','EVOTERIN','TREBYXAN','CAMPTOSAR','CLORITECAN','TECNOTECAN','IRINOTECANO','PROTOITECAN','TOPORAN','HYCAMTIN','TOPOTECANA','EPOSIDO','EUNADES','VEPESID','EVOPOSDO','ETOPOSIDO','TEVAETOPO','ETOPOSIDEO','BONAR','BLEOCEL','BLEOCINS','BLENOXANE','BLEOMYCIN','BLEOMICINA','TECNOMICINA','CABOMETYX','IDA','DACILON','COSMEGEN','DACTINOMICINA','DAUNOCIN','EVOCLASS','DAUNORRUB','DAUNOBLASTINA','DAUNORRUBICINA','DOCKS','DOXOLEN','ONCODOX','RUBIDOX','FAULDOXO','EVORUBICIN','ADRIAMICINA','ADRIBLASTINA','DOXORRUBICINA','CAELYX','DOXOPEG','BRECILA','EPIRRUBICINA','FARMORUBICINA','EVOMID','ZAVEDOS','IDARRUBICINA','MITOCIN','MITOMICINA','EVOMIXAN','MITOXANTRONA','ZYKADIA','TORISEL','VERZENIOS','SPRYCEL','GLIVEC','GLIMATIN','LEUPHILA','IMATINIBE','TASIGNA','ICLUSIG','GIOTRIF','ALECENSA','WELIREG','TARCEVA','IRESSA','TAGRISSO','ALUNBRIG','EVOBRIG','XALKORI','LORBRENA','LORVIQUA','MEKTOVI','COTELLIC','TAFINLAR','MEKINIST','TRAMETINIBE','BRAFTOVI','KOSELUGO','ZELBORAF','IBRANCE','KISQALI','CALQUENCE','IMBRUVICA','CARBOMETYX','TABRECTA','PIQRAY','INLYTA','ERFANDEL','TYKERB','VITRAKVI','LENVIMA','LENVATINIBE','RYDAPT','NERLYNX','VOTRIENT','PAZOPANIBE','STIVARGA','JAKAVI','RETEVMO','NEXAVAR','SUTENT','TEPMETKO','CAPRELSA','BRUKINSA','XOSPATA','ILARIS','LARTRUVO','EMPLICITI','GAZYVA','OBINUTUZUMABE','ELOVIE','AVASTIN','BEVACIZUMABE','PHESGO','PERJETA','PERTUZUMABE','ZEDORA','HERZUMA','KANJINTI','HERCEPTIN','TRAZIMERA','TRASTUZUMABE','TRASTUZUMABE DERUXTECANO','TRASTUZUMABE ENTANSINA','ENHERTU','KADCYLA','ERBITUX','CETUXIMABE','VECTIBIX','PANITUMUMABE','TECENTRIQ','ATEZOLIZUMABE','BAVENCIO','AVELUMABE','LIBTAYO','CEMIPLIMABE','JEMPERLI','IMFINZI','DURVALUMABE','OPDIVO','NIVOLUMABE','KEYTRUDA','PEMBROLIZUMABE','RYBREVANT','QARZIBA','BLINCYTO','BLYNCITO','BLINATUMOMABE','ADCETRIS','BRENTUXIMABE','DALINVI','DARATUMUMABE','UNITUXIN','MYLOTARG','TRODELVY','BESPONSA','SARCLISA','ISATUXIMABE','ROPOLIVY','TECVAYLI','RIXIMYO','TRUXIMA','MABTHERA','RUXIENCE','VIVAXXIA','RITUXIMABE','YERVOY','IPILIMUMABE','PLATAMINE','TEVACARBO','B - PLATIN','FAULDCARBO','PARAPLATIN','CARBOPLATINA','CITOPLAX','CISPLATEX','C - PLATIN','CISPLATINA','PLATISTINE','FAULDCISPLA','OXA','OPLAT','EZULEN','EVOXALI','ELOXATIN','OXALIBBS','BIOEZULEN','COLLECTRO','OXALIMEIZ','TEVAOXALI','OXALIPLATINA','TRETINOINA','ACIDO TRANSRETINOICO','VESANOID','ZOMI','ELOME','TOVAR','VERAZO','BOZORED','VELCADE','MIELOCADE','BORTEZOMIBE','KYPROLIS','CARFILZOMIBE','NINLARO','BELEODAQ','ERIVEDGE','ZEJULA','LYNPARZA','OLAPARIBE','SPECTRILA','ASPARAGINASE','LEUX','TEPEV','HYDREA','HIDROXIUREIA','LISODREN','ONCASPAR','PEGASPARGASE','TRISENOX','TRIOXIDO DE ARSENIO','DESTILBENOL','MEGESTAT','FEMIGESTROL','ZOLADEX','GOSSERRELINA','ELIGARD','LECTRUM','LUPRON DEPOT','LEUPRORRELINA','TRIPTORRELINA','NEO DECAPEPTYL','LEUKINE','ZARZIO','FIPRIMA','FILGRASTIM','FILGRASTINE','GRANULOKINE','TEVAGRASTIM','LONQUEX','LIPEGFILGRASTIM','PELGRAZ','FULPHILA','NEULASTIM','PEGFILGRASTIM','MEPACT','ONCO BCG','IMUNO BCG','VACINA BCG','UROHIPE BCG','MYCOBACTERIUM BOVIS','BACILLUS CALMETTE GUERIN LIOFILIZADO','NUVYOR','REVLIMID','LENALIDOMIDA','IMNOVID','POMALID','POMALYST','NATULAN','PROCARBAZINA','ERWINASE','HALAVEN','ERIBULINA','VENCLEXTA','VENETOCLAX','TIBSOVO','LUMAKRAS','TACFEN','TAMOXIM','TAXOFEN','TECNOTAX','NOLVADEX D','TAMOXIFENO','MATIZ','RARIJA','ZYTIGA','ZOSTIDE','ABIRATERONA','ERLEADA','CASODEX','BICALUTAMIDA','NUBEQA','XTANDI','ARAZABI','ARIMIDEX','ANASTROZOL','ANASTROLIBBS','PROEXTY','AROMASIN','EXEMESTANO','FEMARA','LETROZOL','FIRMAGON','DEGARELIX','POEMMY','SELETIV','VEQUILE','FASLODEX','SUPRENIQ','FULVESTRANTO','HUMIRA','IDACIO','HYRIMOZ','AMGEVITA','XILBRILADA','ADALIMUMABE','CIMZIA','ENBREL','ERELZI','BRENZYS','ENBREL PFS','SIMPONI','AVSOLA','XILFYA','REMSIMA','REMICADE','INFLIXIMABE','BIO MANGUINHOS INFLIXIMABE','OLUMIANT','AFINITOR','CERTICAN','EVEROLIMO','FYARRO','XELJANZ','RINVOQ','AREDIA','FAULDPAMI','TEORO','ZOMETA','ACLASTA','ZOLIBBS','BLAZTERE','ACIDO ZOLEDRONICO','XGEVA','PROLIA','DENOSUMABE','LEUSTATIN','ZALTRAP','FAULDLEUCO') THEN 'ONCOLOGIA'
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN('HYQVIA','CUVITRU','GAMUNEX','OCTAGAM','HIZENTRA','TEGELINE','BLAUIMUNO','INTRATECT','FLEBOGAMMA','PENTAGLOBIN','IMUNOGLOBULIN','SANDOGLOBULINA','ENDOBULIN KIOVIG','EVUSHELD','CYRAMZA','IMJUDO','ENTYVIO','VEDOLIZUMABE','TREMFYA','DUPIXENT','TALTZ','SKYRIZI','COSENTYX','SECUQUINUMABE','STELARA','USTEQUINUMABE','BENLYSTA','ORENCIA','ABATACEPTE','CUPRIMINE','ACTEMRA','LEMTRADA','REBIF','AVONEX','TYSABRI','OCREVUS','KESIMPTA','OFATUMUMABE','REUQUINOL','XOLAIR','FASENRA','NUCALA','MEPOLIZUMABE','OFEV','NINTEDANIBE') THEN 'AUTOIMUNE'
        ELSE 'NAO SE APLICA'
    END AS INS_ESPECIALIDADE_PRIMARIA,

    CASE -- Lógica de ESPECIALIDADE_SECUNDARIA da tb_class_med_final, aplicada ao INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO
        WHEN ipan.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO IN ('RIXIMYO','TRUXIMA','MABTHERA','RUXIENCE','VIVAXXIA','RITUXIMABE','YERVOY','IPILIMUMABE','LEUKINE','ZARZIO','FIPRIMA','FILGRASTIM','FILGRASTINE','GRANULOKINE','TEVAGRASTIM','LONQUEX','LIPEGFILGRASTIM','PELGRAZ','FULPHILA','NEULASTIM','PEGFILGRASTIM','HUMIRA','IDACIO','HYRIMOZ','AMGEVITA','XILBRILADA','ADALIMUMABE','CIMZIA','ENBREL','ERELZI','BRENZYS','ENBREL PFS','SIMPONI','AVSOLA','XILFYA','REMSIMA','REMICADE','INFLIXIMABE','BIO MANGUINHOS INFLIXIMABE','OLUMIANT','XELJANZ','RINVOQ') THEN 'AUTOIMUNE'
        ELSE 'NAO SE APLICA'
    END AS INS_ESPECIALIDADE_SECUNDARIA
FROM tab ipan
),
------------------------------------------ 
-- 
-- CTEs TB_JUNCAO_ONCO_IMUNO, TB_ESP_MEDICAMENTO, TB_ESP_MEDICAMENTO_AJUSTAR, tb_class_med_final 
--são tabelas  especificsa que estou usando para fazer a classificação da insumo
------------------------------------------
TB_JUNCAO_ONCO_IMUNO AS
(
    SELECT DISTINCT
    COD_SERVICO_MATERIAL_MEDICAMENTO,
    DSC_SERVICO_MATERIAL_MEDICAMENTO_ORIGEM AS DSC_SERVICO_MEDICAMENTO,
    DSC_MEDICAMENTO AS DSC_PADRAO_SERVICO_MEDICAMENTO,
    DSC_PRINCIPIO_ATIVO AS DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
    CASE WHEN DSC_MEDICAMENTO IN('RITUXIMABE','RIXIMYO','TRUXIMA','VIVAXXIA','MABTHERA','RUXIENCE')  THEN '1'ELSE '0' END AS FLG_VINCULO_CODIGO_TUSS,
    CASE WHEN DSC_MEDICAMENTO IN('RITUXIMABE','RIXIMYO','TRUXIMA','VIVAXXIA') THEN 'IMUNOBIOLOGICO,ONCOLOGICO'
          WHEN DSC_MEDICAMENTO IN('MABTHERA','RUXIENCE') THEN 'IMUNOBIOLOGICO,NAO EXCLUSIVO ONCOLOGIA'
    ELSE DSC_CLASSIFICACAO_MEDICAMENTO END AS DSC_CLASSIFICACAO_MEDICAMENTO,

    CASE WHEN DSC_MEDICAMENTO IN('RITUXIMABE','RIXIMYO','TRUXIMA','VIVAXXIA','MABTHERA','RUXIENCE') THEN 'IMUNOBIOLOGICO,IMUNOTERAPIA'
    ELSE DSC_SUBCLASSIFICACAO_MEDICAMENTO END AS DSC_SUBCLASSIFICACAO_MEDICAMENTO, 
    DSC_CLASSIFICACAO_VIA_ACESSO,
    DSC_TIPO_CANCER
    FROM tab

    UNION ALL

    SELECT DISTINCT
    COD_SERVICO_IMUNOBIOLOGICO AS COD_SERVICO_MATERIAL_MEDICAMENTO,
    DSC_SERVICO_IMUNOBIOLOGICO AS DSC_SERVICO_MEDICAMENTO,
    DSC_PADRAO_SERVICO_MEDICAMENTO,
    CASE WHEN DSC_PRINCIPIO_ATIVO_MEDICAMENTO = 'RUXIENCE' THEN 'RITUXIMABE'
        WHEN DSC_PRINCIPIO_ATIVO_MEDICamento =  'IMUNOGLOBULINA G' THEN 'IMUNOGLOBULINA HUMANA'ELSE DSC_PRINCIPIO_ATIVO_MEDICAMENTO END AS DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
    FLG_VINCULO_CODIGO_TUSS,
    CASE WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('RITUXIMABE','RIXIMYO','TRUXIMA','VIVAXXIA') THEN 'IMUNOBIOLOGICO,ONCOLOGICO'
          WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('MABTHERA','RUXIENCE') THEN 'IMUNOBIOLOGICO,NAO EXCLUSIVO ONCOLOGIA'
    ELSE 'IMUNOBIOLOGICO' END AS DSC_CLASSIFICACAO_MEDICAMENTO,
    
    CASE WHEN DSC_PRINCIPIO_ATIVO_MEDICAMENTO IN('IMUNOGLOBULINA HUMANA','IMUNOGLOBULINA G') THEN 'IMUNOGLOBULINA' 
        WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('RITUXIMABE','RIXIMYO','TRUXIMA','VIVAXXIA','MABTHERA','RUXIENCE') THEN 'IMUNOBIOLOGICO,IMUNOTERAPIA' 
    ELSE 'IMUNOBIOLOGICO' END AS DSC_SUBCLASSIFICACAO_MEDICAMENTO,
    CASE WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('MABTHERA','RITUXIMABE','TRUXIMA','VIVAXXIA') THEN  'EV'
        WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('RUXIENCE','RIXIMYO') THEN 'SC' 
    ELSE '' END AS DSC_CLASSIFICACAO_VIA_ACESSO,
    'NAO MAPEADO' AS DSC_TIPO_CANCER
    FROM tab
  --39.394
)
,TB_ESP_MEDICAMENTO AS
(
  SELECT
  COD_SERVICO_MATERIAL_MEDICAMENTO,
  DSC_SERVICO_MEDICAMENTO,
  DSC_PADRAO_SERVICO_MEDICAMENTO,
  DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
  MAX(FLG_VINCULO_CODIGO_TUSS) AS FLG_VINCULO_CODIGO_TUSS,
  STRING_AGG(DISTINCT DSC_CLASSIFICACAO_MEDICAMENTO ORDER BY DSC_CLASSIFICACAO_MEDICAMENTO) AS DSC_CLASSIFICACAO_MEDICAMENTO,
  STRING_AGG(DISTINCT DSC_SUBCLASSIFICACAO_MEDICAMENTO ORDER BY DSC_SUBCLASSIFICACAO_MEDICAMENTO) AS DSC_SUBCLASSIFICACAO_MEDICAMENTO,
  STRING_AGG(DISTINCT DSC_CLASSIFICACAO_VIA_ACESSO ,'' ORDER BY DSC_CLASSIFICACAO_VIA_ACESSO) AS DSC_CLASSIFICACAO_VIA_ACESSO,
  STRING_AGG(DISTINCT DSC_TIPO_CANCER ,'' ORDER BY DSC_TIPO_CANCER) AS DSC_CLASSIFICACAO_TIPO_CANCER
  FROM TB_JUNCAO_ONCO_IMUNO
  GROUP BY ALL
)
,TB_ESP_MEDICAMENTO_AJUSTAR AS
(
  SELECT
  COD_SERVICO_MATERIAL_MEDICAMENTO,
  DSC_SERVICO_MEDICAMENTO,
  DSC_PADRAO_SERVICO_MEDICAMENTO,
  DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
  FLG_VINCULO_CODIGO_TUSS,
  DSC_CLASSIFICACAO_MEDICAMENTO,
  CASE 
      WHEN DSC_CLASSIFICACAO_MEDICAMENTO IN('ONCOLOGICO','ADJUVANTE','SUPORTE','NAO EXCLUSIVO ONCOLOGIA') THEN 'ONCOLOGIA'
      WHEN DSC_CLASSIFICACAO_MEDICAMENTO = 'IMUNOBIOLOGICO' THEN 'IMUNOBIOLOGICO'
      WHEN DSC_CLASSIFICACAO_MEDICAMENTO IN('IMUNOBIOLOGICO,ONCOLOGICO','IMUNOBIOLOGICO,NAO EXCLUSIVO ONCOLOGIA') THEN 'IMUNOBIOLOGICO E ONCOLOGIA' 
  END AS DSC_CLASSIFICACAO_MEDICAMENTO_AGRUPADO,
  DSC_SUBCLASSIFICACAO_MEDICAMENTO AS DSC_PADRAO_CLASSIFICACAO_MEDICAMENTO, 
  DSC_CLASSIFICACAO_VIA_ACESSO,
  DSC_CLASSIFICACAO_TIPO_CANCER
  FROM TB_ESP_MEDICAMENTO 
 --38616
)
-- CTE de classificação final da especifica
,especifica_classificacao_final AS (
  SELECT
  *, 
  CASE 
  WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ABATACEPTE','ACTEMRA','ADALIMUMABE','ADCETRIS','AMGEVITA','ATEZOLIZUMABE','AVASTIN','AVELUMABE','AVONEX','AVSOLA','BACILLUS CALMETTE GUERIN LIOFILIZADO','BAVENCIO','BENLYSTA','BESPONSA','BEVACIZUMABE','BIO MANGUINHOS INFLIXIMABE','BLAUIMUNO','BLINATUMOMABE','BLINCYTO','BLYNCITO','BRENTUXIMABE','BRENZYS','CEMIPLIMABE','CETUXIMABE','CIMZIA','COSENTYX','CUVITRU','CYRAMZA','DALINVI','DARATUMUMABE','DUPIXENT','DURVALUMABE','ELOVIE','EMPLICITI','ENBREL','ENBREL PFS','ENDOBULIN KIOVIG','ENDOBULIN KIOVIG','ENHERTU','ENTYVIO','ERBITUX','ERELZI','EVUSHELD','FASENRA','FLEBOGAMMA','GAMUNEX','GAMUNEX','GAZYVA','HERCEPTIN','HERZUMA','HIZENTRA','HUMIRA','HYQVIA','HYQVIA','HYRIMOZ','IDACIO','ILARIS','IMFINZI','IMJUDO','IMUNO BCG','IMUNOGLOBULIN','IMUNOGLOBULIN','INFLIXIMABE','INTRATECT','IPILIMUMABE','ISATUXIMABE','JEMPERLI','KADCYLA','KANJINTI','KESIMPTA','KEYTRUDA','LARTRUVO','LEMTRADA','LIBTAYO','MABTHERA','MABTHERA','MABTHERA','MEPACT','MEPOLIZUMABE','MYCOBACTERIUM BOVIS','MYLOTARG','NIVOLUMABE','NUCALA','OBINUTUZUMABE','OCREVUS','OCTAGAM','OFATUMUMABE','ONCO BCG','OPDIVO','ORENCIA','PANITUMUMABE','PEMBROLIZUMABE','PENTAGLOBIN','PERJETA','PERTUZUMABE','PHESGO','ROPOLIVY','QARZIBA','REBIF','REMICADE','REMSIMA','RITUXIMABE','RITUXIMABE','RIXIMYO','RIXIMYO','RIXIMYO','RUXIENCE','RYBREVANT','SANDOGLOBULINA','SARCLISA','SECUQUINUMABE','SIMPONI','SKYRIZI','STELARA','TALTZ','TECENTRIQ','TECVAYLI','TEGELINE','TRASTUZUMABE','TRASTUZUMABE DERUXTECANO','TRASTUZUMABE ENTANSINA','TRAZIMERA','TREMFYA','TRODELVY','TRUXIMA','TRUXIMA','TYSABRI','UNITUXIN','UROHIPE BCG','USTEQUINUMABE','VACINA BCG','VECTIBIX','VEDOLIZUMABE','VIVAXXIA','VIVAXXIA','XILBRILADA','XILFYA','XOLAIR','YERVOY','ZEDORA') THEN 'IMUNOTERAPIA - IMUNOBIOLOGICO'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('IMNOVID','LENALIDOMIDA','NUVYOR','POMALID','POMALYST','REVLIMID') THEN 'IMUNOTERAPIA - NAO IMUNOBIOLOGICO'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ACIDO ZOLEDRONICO','ACLASTA','AKYNZEO','ALFAEPOETINA','ARANESP','AREDIA','BLAZTERE','CUPRIMINE','DENOSUMABE','EPREX','ERITROMAX','ERITROPOETINA','FAULDLEUCO','FAULDPAMI','HEMAX','NETUPITANTO','ONTRAX','PROLIA','REUQUINOL','TECNOCARB','TEORO','TEPADINA','XGEVA','ZOLIBBS','ZOMETA') THEN 'MEDICAMENTO DE SUPORTE'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('FILGRASTIM','FILGRASTINE','FIPRIMA','FULPHILA','GRANULOKINE','LEUKINE','LIPEGFILGRASTIM','LONQUEX','NEULASTIM','PEGFILGRASTIM','PELGRAZ','TEVAGRASTIM','ZARZIO') THEN 'MEDICAMENTO DE SUPORTE IMUNOBIOLOGICO'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ABRAXANE','ACIDO TRANSRETINOICO','ADRIAMICINA','ADRIBLASTINA','ALIMTA','ALKERAN','ARACYTIN','ASPARAGINASE','ATRED','AZACITIDINA','B - PLATIN','BECENUN','BENALQ','BENDAMUSTINA','BICNU','BIOEZULEN','BLENOXANE','BLEOCEL','BLEOCINS','BLEOMICINA','BLEOMYCIN','BONAR','BRECILA','BUCELON','BUSILVEX','BUSSULFANO','BUSULFEX','C - PLATIN','CAAB','CABAZITAXEL','CABAZRED','CAELYX','CAMPTOSAR','CAPECITABINA','CARBOPLATINA','CARMUSTINA','CICLOFOSFAMIDA','CISPLATEX','CISPLATINA','CITARABINA','CITARAX','CITOPLAX','CITOSTAL','CLORITECAN','COLLECTRO','CORRETAL','COSMEGEN','DACARB','DACARBAZINA','DACILON','DACOGEN','DACTINOMICINA','DAUNOBLASTINA','DAUNOCIN','DAUNORRUB','DAUNORRUBICINA','DECITABINA','DETIMEDAC','DOCELIBBS','DOCETAXEL','DOCEUNO','DOCKS','DOXOLEN','DOXOPEG','DOXORRUBICINA','ELOXATIN','EPIRRUBICINA','EPOSIDO','EROXYM','ERWINASE','ETOPOSIDEO','ETOPOSIDO','EUNADES','EVOCLASS','EVODAZIN','EVOFLUBINA','EVOLOX','EVOMID','EVOMIXAN','EVOPOSDO','EVORUBICIN','EVOTABINA','EVOTAXEL','EVOTERIN','EVOXALI','EVOZAR','EZULEN','FARMORUBICINA','FAULBLASTINA','FAULDACAR','FAULDCARBO','FAULDCISPLA','FAULDCITA','FAULDFLUOR','FAULDMETRO','FAULDOXO','FAULDVINCRI','FLUDALIBBS','FLUDARA','FLUDARABINA','FLUORURACILA','FLUSAN','GCIB','GEMCIT','GEMZAR','GENABYX','GENCITABINA','GENCIX','GENLIBBS','GENUXAL','HIDROXIUREIA','HOLOXANE','HYCAMTIN','HYDREA','HYTAS','IDA','IDARRUBICINA','IFOSFAMIDA','IRINOTECANO','IRNOCAM','IRO','JAVLOR','JEVTANA','LANVIS','LEUKERAN','LEUSTATIN','LEUX','LEVACT','LIFOS','LISODREN','LONSURF','MELFALANO','MELPHALAN','MERCAPTOPURINA','MESOTEM','METOTREXATO','METREXATO','MIANTREX','MITOCIN','MITOMICINA','MITOXANTRONA','MTX','MUPHORAN','NATULAN','NAVELBINE','NEOCITEC','NIBISNU','NORELBIN','ONCASPAR','ONCODOCEL','ONCODOX','ONCOVIN','ONIVYDE','ONTAX','OPLAT','OXA','OXALIBBS','OXALIMEIZ','OXALIPLATINA','PACLITAX','PACLITAXEL','PARAPLATIN','PAREXEL','PEGASPARGASE','PEMEGLENN','PEMETREXEDE','PEMTRYX','PLATAMINE','PLATISTINE','PLEXEDEN','PROAZITAX','PROCARBAZINA','PROTOITECAN','PURINETHOL','RABINEFIL','REDTIBIN','RIBOMUSTIN','RUBIDOX','SPECTRILA','SUKHI','TACE','TARVEXOL','TAXILAN','TAXOL','TAXOTERE','TECNOCRIS','TECNOMICINA','TECNOTECAN','TEMODAL','TEMOLIDA','TEMOZOLOMIDA','TEPEV','TEVACARBO','TEVAETOPO','TEVAMETHO','TEVAOXALI','TIOTEPA','TOPORAN','TOPOTECANA','TREBYXAN','TRETINOINA','TRIOXIDO DE ARSENIO','TRISENOX','VANCEL','VELBAN','VEPESID','VESANOID','VIDAZA','VILNE','VIMBLASTINA','VINCIZINA','VINCRISTINA','VINORELBINA','WINDUZA','XELODA','YONDELIS','ZAVEDOS') THEN 'QUIMIOTERAPICO'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('AFINITOR','ALECENSA','ALUNBRIG','BELEODAQ','BORTEZOMIBE','BOZORED','BRAFTOVI','BRUKINSA','CABOMETYX','CALQUENCE','CAPRELSA','CARBOMETYX','CARFILZOMIBE','CERTICAN','COTELLIC','ELOME','ERFANDEL','ERIBULINA','ERIVEDGE','EVEROLIMO','EVOBRIG','FYARRO','GIOTRIF','GLIMATIN','GLIVEC','HALAVEN','IBRANCE','ICLUSIG','IMATINIBE','IMBRUVICA','INLYTA','IRESSA','JAKAVI','KISQALI','KOSELUGO','KYPROLIS','LENVATINIBE','LENVIMA','LEUPHILA','LORBRENA','LORVIQUA','LUMAKRAS','LYNPARZA','MEKINIST','MEKTOVI','MIELOCADE','NERLYNX','NEXAVAR','NINLARO','NINTEDANIBE','OFEV','OLAPARIBE','OLUMIANT','PAZOPANIBE','PIQRAY','RETEVMO','RINVOQ','RYDAPT','SPRYCEL','STIVARGA','SUTENT','TABRECTA','TAFINLAR','TAGRISSO','TARCEVA','TASIGNA','TEPMETKO','TIBSOVO','TORISEL','TOVAR','TRAMETINIBE','TYKERB','VELCADE','VENCLEXTA','VENETOCLAX','VERAZO','VERZENIOS','VITRAKVI','VOTRIENT','WELIREG','XALKORI','XELJANZ','XOSPATA','ZALTRAP','ZEJULA','ZELBORAF','ZOMI','ZYKADIA') THEN 'TERAPIA ALVO - DROGAS SINTETICAS'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ABIRATERONA','ANASTROLIBBS','ANASTROZOL','ARAZABI','ARIMIDEX','AROMASIN','BICALUTAMIDA','CASODEX','CINACALCETE','DEGARELIX','DESTILBENOL','ELIGARD','ERLEADA','EXEMESTANO','FASLODEX','FEMARA','FEMIGESTROL','FIRMAGON','FULVESTRANTO','GOSSERRELINA','LANREOTIDA','LECTRUM','LETROZOL','LEUPRORRELINA','LUPRON DEPOT','MATIZ','MEGESTAT','NEO DECAPEPTYL','NOLVADEX D','NUBEQA','OCTREOTIDA','OCTRIDE','POEMMY','PROEXTY','RARIJA','SANDOSTATIN','SELETIV','SOMATULINE','SUPRENIQ','TACFEN','TAMOXIFENO','TAMOXIM','TAXOFEN','TECNOTAX','TRIPTORRELINA','VEQUILE','XTANDI','ZOLADEX','ZOSTIDE','ZYTIGA') THEN 'TERAPIA ENDOCRINA'
ELSE 'REVER'
END AS DSC_CLASSIFICACAO_MEDICAMENTO_NOVA,

CASE 
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('TECNOCARB','TEPADINA','LEVACT','RIBOMUSTIN','BENDAMUSTINA','BUSILVEX','BUSULFEX','BUSSULFANO','BUCELON','VANCEL','BICNU','BECENUN','NIBISNU','CARMUSTINA','DACARB','EVODAZIN','DETIMEDAC','FAULDACAR','DACARBAZINA','MUPHORAN','LIFOS','EVOLOX','HOLOXANE','IFOSFAMIDA','TEMOLIDA','TIOTEPA','CITARAX','FAULDCITA','CITARABINA','DACOGEN','REDTIBIN','DECITABINA','FLUDARA','EVOFLUBINA','FLUDALIBBS','FLUDARABINA','FLUSAN','FAULDFLUOR','FLUORURACILA','GCIB','EVOZAR','GEMCIT','GEMZAR','GENCIX','GENABYX','GENLIBBS','GENCITABINA','ATRED','SUKHI','ALIMTA','EROXYM','MESOTEM','PEMTRYX','PLEXEDEN','PEMEGLENN','PEMETREXEDE','YONDELIS','VELBAN','RABINEFIL','VIMBLASTINA','FAULBLASTINA','ONCOVIN','TECNOCRIS','VINCIZINA','FAULDVINCRI','VINCRISTINA','JAVLOR','VILNE','NEOCITEC','NORELBIN','EVOTABINA','NAVELBINE','VINORELBINA','TACE','DOCEUNO','TAXOTERE','DOCELIBBS','DOCETAXEL','ONCODOCEL','ONTAX','TAXOL','PAREXEL','TAXILAN','EVOTAXEL','PACLITAX','TARVEXOL','PACLITAXEL','ABRAXANE','CABAZRED','PROAZITAX','CABAZITAXEL','CAAB','JEVTANA','IRO','IRNOCAM','ONIVYDE','EVOTERIN','TREBYXAN','CAMPTOSAR','CLORITECAN','TECNOTECAN','IRINOTECANO','PROTOITECAN','TOPORAN','HYCAMTIN','TOPOTECANA','TEVAETOPO','BONAR','BLEOCEL','BLEOCINS','BLENOXANE','BLEOMYCIN','BLEOMICINA','TECNOMICINA','IDA','DACILON','COSMEGEN','DACTINOMICINA','DAUNOCIN','EVOCLASS','DAUNORRUB','DAUNOBLASTINA','DAUNORRUBICINA','DOCKS','DOXOLEN','ONCODOX','RUBIDOX','FAULDOXO','EVORUBICIN','ADRIAMICINA','ADRIBLASTINA','DOXORRUBICINA','CAELYX','DOXOPEG','BRECILA','EPIRRUBICINA','FARMORUBICINA','EVOMID','ZAVEDOS','IDARRUBICINA','MITOCIN','MITOMICINA','EVOMIXAN','MITOXANTRONA','TORISEL','CARBOMETYX','LARTRUVO','EMPLICITI','GAZYVA','OBINUTUZUMABE','ELOVIE','AVASTIN','BEVACIZUMABE','PERJETA','PERTUZUMABE','ZEDORA','HERZUMA','KANJINTI','HERCEPTIN','TRAZIMERA','TRASTUZUMABE','TRASTUZUMABE DERUXTECANO','TRASTUZUMABE ENTANSINA','ENHERTU','KADCYLA','ERBITUX','CETUXIMABE','VECTIBIX','PANITUMUMABE','TECENTRIQ','ATEZOLIZUMABE','BAVENCIO','AVELUMABE','LIBTAYO','CEMIPLIMABE','JEMPERLI','IMFINZI','DURVALUMABE','OPDIVO','NIVOLUMABE','KEYTRUDA','PEMBROLIZUMABE','RYBREVANT','QARZIBA','BLINCYTO','BLYNCITO','BLINATUMOMABE','ADCETRIS','BRENTUXIMABE','DALINVI','DARATUMUMABE','UNITUXIN','MYLOTARG','TRODELVY','BESPONSA','SARCLISA','ISATUXIMABE','ROPOLIVY','TECVAYLI','TRUXIMA','MABTHERA','VIVAXXIA','RITUXIMABE','CYRAMZA','YERVOY','IPILIMUMABE','IMJUDO','PLATAMINE','TEVACARBO','B - PLATIN','FAULDCARBO','PARAPLATIN','CARBOPLATINA','CITOPLAX','CISPLATEX','C - PLATIN','CISPLATINA','PLATISTINE','FAULDCISPLA','OXA','OPLAT','EZULEN','EVOXALI','ELOXATIN','OXALIBBS','COLLECTRO','OXALIMEIZ','TEVAOXALI','OXALIPLATINA','KYPROLIS','CARFILZOMIBE','BELEODAQ','SPECTRILA','ASPARAGINASE','PEGASPARGASE','TRISENOX','TRIOXIDO DE ARSENIO','MEPACT','ERWINASE','HALAVEN','ERIBULINA','AREDIA','FAULDPAMI','TEORO','ZOMETA','ACLASTA','ZOLIBBS','BLAZTERE','ACIDO ZOLEDRONICO','LEUSTATIN','OFATUMUMABE','ZALTRAP','FAULDLEUCO') THEN 'EV'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ONCASPAR') THEN 'EV / IM'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('EPREX','HEMAX','ERITROMAX','ARANESP','OCTRIDE','OCTREOTIDA','SANDOSTATIN','VIDAZA','WINDUZA','AZACITIDINA','ZOMI','ELOME','TOVAR','VERAZO','BOZORED','VELCADE','MIELOCADE','BORTEZOMIBE','LEUKINE','FIPRIMA','FILGRASTIM','FILGRASTINE','GRANULOKINE','ARAZABI') THEN 'EV / SC'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ARACYTIN') THEN 'EV / SC / IT' 
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ELIGARD','LECTRUM','LUPRON DEPOT','LEUPRORRELINA') THEN 'IM / SC'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('TRIPTORRELINA','NEO DECAPEPTYL','ONCO BCG','IMUNO BCG','VACINA BCG','UROHIPE BCG','MYCOBACTERIUM BOVIS','POEMMY','SELETIV','FASLODEX','SUPRENIQ','FULVESTRANTO') THEN 'IM'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('BACILLUS CALMETTE GUERIN LIOFILIZADO') THEN 'INTRAVESICAL'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ONTRAX','GENUXAL','CICLOFOSFAMIDA','ALKERAN','MELFALANO','MELPHALAN','TEMODAL','TEMOZOLOMIDA','MTX','HYTAS','MIANTREX','METREXATO','TEVAMETHO','FAULDMETRO','METOTREXATO','EPOSIDO','EUNADES','EVOPOSDO','ETOPOSIDO','ETOPOSIDEO') THEN 'EV / VO'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('AKYNZEO','NETUPITANTO','CINACALCETE','BENALQ','LEUKERAN','CITOSTAL','CAPECITABINA','PURINETHOL','MERCAPTOPURINA','LANVIS','LONSURF','XELODA','CORRETAL','VEPESID','CABOMETYX','ZYKADIA','VERZENIOS','SPRYCEL','GLIVEC','GLIMATIN','LEUPHILA','IMATINIBE','TASIGNA','ICLUSIG','GIOTRIF','ALECENSA','WELIREG','TARCEVA','IRESSA','TAGRISSO','ALUNBRIG','EVOBRIG','XALKORI','LORBRENA','LORVIQUA','MEKTOVI','COTELLIC','TAFINLAR','MEKINIST','TRAMETINIBE','BRAFTOVI','KOSELUGO','ZELBORAF','IBRANCE','KISQALI','CALQUENCE','IMBRUVICA','TABRECTA','PIQRAY','INLYTA','ERFANDEL','TYKERB','VITRAKVI','LENVIMA','LENVATINIBE','RYDAPT','NERLYNX','VOTRIENT','PAZOPANIBE','STIVARGA','JAKAVI','RETEVMO','NEXAVAR','SUTENT','TEPMETKO','CAPRELSA','BRUKINSA','XOSPATA','BIOEZULEN','TRETINOINA','ACIDO TRANSRETINOICO','VESANOID','NINLARO','ERIVEDGE','ZEJULA','LYNPARZA','OLAPARIBE','LEUX','TEPEV','HYDREA','HIDROXIUREIA','LISODREN','DESTILBENOL','MEGESTAT','FEMIGESTROL','NUVYOR','REVLIMID','LENALIDOMIDA','IMNOVID','POMALID','POMALYST','NATULAN','PROCARBAZINA','VENCLEXTA','VENETOCLAX','TIBSOVO','LUMAKRAS','TACFEN','TAMOXIM','TAXOFEN','TECNOTAX','NOLVADEX D','TAMOXIFENO','MATIZ','RARIJA','ZYTIGA','ZOSTIDE','ABIRATERONA','ERLEADA','CASODEX','BICALUTAMIDA','NUBEQA','XTANDI','ARIMIDEX','ANASTROZOL','ANASTROLIBBS','PROEXTY','AROMASIN','EXEMESTANO','FEMARA','LETROZOL','VEQUILE','AFINITOR','CERTICAN','EVEROLIMO','FYARRO','OFEV','NINTEDANIBE') THEN 'VO'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('ALFAEPOETINA','ERITROPOETINA','LANREOTIDA','SOMATULINE','PHESGO','RIXIMYO','RIXIMYO','RUXIENCE','ZOLADEX','GOSSERRELINA','ZARZIO','TEVAGRASTIM','LONQUEX','LIPEGFILGRASTIM','PELGRAZ','FULPHILA','NEULASTIM','PEGFILGRASTIM','FIRMAGON','DEGARELIX','XGEVA','PROLIA','DENOSUMABE','KESIMPTA') THEN 'SC'
ELSE 'NAO SE APLICA' END AS DSC_CLASSIFICACAO_VIA_ACESSO_NOVA,

CASE WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('EPREX','HEMAX','ERITROMAX','ARANESP','ALFAEPOETINA','ERITROPOETINA','LANREOTIDA','SOMATULINE','OCTRIDE','OCTREOTIDA','SANDOSTATIN','CINACALCETE','BENALQ','LEVACT','RIBOMUSTIN','BENDAMUSTINA','BUSILVEX','BUSULFEX','BUSSULFANO','BUCELON','VANCEL','BICNU','BECENUN','NIBISNU','CARMUSTINA','GENUXAL','CICLOFOSFAMIDA','LEUKERAN','DACARB','EVODAZIN','DETIMEDAC','FAULDACAR','DACARBAZINA','MUPHORAN','LIFOS','EVOLOX','HOLOXANE','IFOSFAMIDA','CITOSTAL','ALKERAN','MELFALANO','MELPHALAN','TEMODAL','TEMOLIDA','TEMOZOLOMIDA','TIOTEPA','CAPECITABINA','VIDAZA','WINDUZA','AZACITIDINA','CITARAX','ARACYTIN','FAULDCITA','CITARABINA','DACOGEN','REDTIBIN','DECITABINA','FLUDARA','EVOFLUBINA','FLUDALIBBS','FLUDARABINA','FLUSAN','FAULDFLUOR','FLUORURACILA','GCIB','EVOZAR','GEMCIT','GEMZAR','GENCIX','GENABYX','GENLIBBS','GENCITABINA','PURINETHOL','MERCAPTOPURINA','MTX','HYTAS','MIANTREX','METREXATO','TEVAMETHO','FAULDMETRO','METOTREXATO','ATRED','SUKHI','ALIMTA','EROXYM','MESOTEM','PEMTRYX','PLEXEDEN','PEMEGLENN','PEMETREXEDE','LANVIS','LONSURF','XELODA','CORRETAL','YONDELIS','VELBAN','RABINEFIL','VIMBLASTINA','FAULBLASTINA','ONCOVIN','TECNOCRIS','VINCIZINA','FAULDVINCRI','VINCRISTINA','JAVLOR','VILNE','NEOCITEC','NORELBIN','EVOTABINA','NAVELBINE','VINORELBINA','TACE','DOCEUNO','TAXOTERE','DOCELIBBS','DOCETAXEL','ONCODOCEL','ONTAX','TAXOL','PAREXEL','TAXILAN','EVOTAXEL','PACLITAX','TARVEXOL','PACLITAXEL','ABRAXANE','CABAZRED','PROAZITAX','CABAZITAXEL','CAAB','JEVTANA','IRO','IRNOCAM','ONIVYDE','EVOTERIN','TREBYXAN','CAMPTOSAR','CLORITECAN','TECNOTECAN','IRINOTECANO','PROTOITECAN','TOPORAN','HYCAMTIN','TOPOTECANA','EPOSIDO','EUNADES','VEPESID','EVOPOSDO','ETOPOSIDO','TEVAETOPO','ETOPOSIDEO','BONAR','BLEOCEL','BLEOCINS','BLENOXANE','BLEOMYCIN','BLEOMICINA','TECNOMICINA','CABOMETYX','IDA','DACILON','COSMEGEN','DACTINOMICINA','DAUNOCIN','EVOCLASS','DAUNORRUB','DAUNOBLASTINA','DAUNORRUBICINA','DOCKS','DOXOLEN','ONCODOX','RUBIDOX','FAULDOXO','EVORUBICIN','ADRIAMICINA','ADRIBLASTINA','DOXORRUBICINA','CAELYX','DOXOPEG','BRECILA','EPIRRUBICINA','FARMORUBICINA','EVOMID','ZAVEDOS','IDARRUBICINA','MITOCIN','MITOMICINA','EVOMIXAN','MITOXANTRONA','ZYKADIA','TORISEL','VERZENIOS','SPRYCEL','GLIVEC','GLIMATIN','LEUPHILA','IMATINIBE','TASIGNA','ICLUSIG','GIOTRIF','ALECENSA','WELIREG','TARCEVA','IRESSA','TAGRISSO','ALUNBRIG','EVOBRIG','XALKORI','LORBRENA','LORVIQUA','MEKTOVI','COTELLIC','TAFINLAR','MEKINIST','TRAMETINIBE','BRAFTOVI','KOSELUGO','ZELBORAF','IBRANCE','KISQALI','CALQUENCE','IMBRUVICA','CARBOMETYX','TABRECTA','PIQRAY','INLYTA','ERFANDEL','TYKERB','VITRAKVI','LENVIMA','LENVATINIBE','RYDAPT','NERLYNX','VOTRIENT','PAZOPANIBE','STIVARGA','JAKAVI','RETEVMO','NEXAVAR','SUTENT','TEPMETKO','CAPRELSA','BRUKINSA','XOSPATA','ILARIS','LARTRUVO','EMPLICITI','GAZYVA','OBINUTUZUMABE','ELOVIE','AVASTIN','BEVACIZUMABE','PHESGO','PERJETA','PERTUZUMABE','ZEDORA','HERZUMA','KANJINTI','HERCEPTIN','TRAZIMERA','TRASTUZUMABE','TRASTUZUMABE DERUXTECANO','TRASTUZUMABE ENTANSINA','ENHERTU','KADCYLA','ERBITUX','CETUXIMABE','VECTIBIX','PANITUMUMABE','TECENTRIQ','ATEZOLIZUMABE','BAVENCIO','AVELUMABE','LIBTAYO','CEMIPLIMABE','JEMPERLI','IMFINZI','DURVALUMABE','OPDIVO','NIVOLUMABE','KEYTRUDA','PEMBROLIZUMABE','RYBREVANT','QARZIBA','BLINCYTO','BLYNCITO','BLINATUMOMABE','ADCETRIS','BRENTUXIMABE','DALINVI','DARATUMUMABE','UNITUXIN','MYLOTARG','TRODELVY','BESPONSA','SARCLISA','ISATUXIMABE','ROPOLIVY','TECVAYLI','RIXIMYO','TRUXIMA','MABTHERA','RUXIENCE','VIVAXXIA','RITUXIMABE','YERVOY','IPILIMUMABE','PLATAMINE','TEVACARBO','B - PLATIN','FAULDCARBO','PARAPLATIN','CARBOPLATINA','CITOPLAX','CISPLATEX','C - PLATIN','CISPLATINA','PLATISTINE','FAULDCISPLA','OXA','OPLAT','EZULEN','EVOXALI','ELOXATIN','OXALIBBS','BIOEZULEN','COLLECTRO','OXALIMEIZ','TEVAOXALI','OXALIPLATINA','TRETINOINA','ACIDO TRANSRETINOICO','VESANOID','ZOMI','ELOME','TOVAR','VERAZO','BOZORED','VELCADE','MIELOCADE','BORTEZOMIBE','KYPROLIS','CARFILZOMIBE','NINLARO','BELEODAQ','ERIVEDGE','ZEJULA','LYNPARZA','OLAPARIBE','SPECTRILA','ASPARAGINASE','LEUX','TEPEV','HYDREA','HIDROXIUREIA','LISODREN','ONCASPAR','PEGASPARGASE','TRISENOX','TRIOXIDO DE ARSENIO','DESTILBENOL','MEGESTAT','FEMIGESTROL','ZOLADEX','GOSSERRELINA','ELIGARD','LECTRUM','LUPRON DEPOT','LEUPRORRELINA','TRIPTORRELINA','NEO DECAPEPTYL','LEUKINE','ZARZIO','FIPRIMA','FILGRASTIM','FILGRASTINE','GRANULOKINE','TEVAGRASTIM','LONQUEX','LIPEGFILGRASTIM','PELGRAZ','FULPHILA','NEULASTIM','PEGFILGRASTIM','MEPACT','ONCO BCG','IMUNO BCG','VACINA BCG','UROHIPE BCG','MYCOBACTERIUM BOVIS','BACILLUS CALMETTE GUERIN LIOFILIZADO','NUVYOR','REVLIMID','LENALIDOMIDA','IMNOVID','POMALID','POMALYST','NATULAN','PROCARBAZINA','ERWINASE','HALAVEN','ERIBULINA','VENCLEXTA','VENETOCLAX','TIBSOVO','LUMAKRAS','TACFEN','TAMOXIM','TAXOFEN','TECNOTAX','NOLVADEX D','TAMOXIFENO','MATIZ','RARIJA','ZYTIGA','ZOSTIDE','ABIRATERONA','ERLEADA','CASODEX','BICALUTAMIDA','NUBEQA','XTANDI','ARAZABI','ARIMIDEX','ANASTROZOL','ANASTROLIBBS','PROEXTY','AROMASIN','EXEMESTANO','FEMARA','LETROZOL','FIRMAGON','DEGARELIX','POEMMY','SELETIV','VEQUILE','FASLODEX','SUPRENIQ','FULVESTRANTO','HUMIRA','IDACIO','HYRIMOZ','AMGEVITA','XILBRILADA','ADALIMUMABE','CIMZIA','ENBREL','ERELZI','BRENZYS','ENBREL PFS','SIMPONI','AVSOLA','XILFYA','REMSIMA','REMICADE','INFLIXIMABE','BIO MANGUINHOS INFLIXIMABE','OLUMIANT','AFINITOR','CERTICAN','EVEROLIMO','FYARRO','XELJANZ','RINVOQ','AREDIA','FAULDPAMI','TEORO','ZOMETA','ACLASTA','ZOLIBBS','BLAZTERE','ACIDO ZOLEDRONICO','XGEVA','PROLIA','DENOSUMABE','LEUSTATIN','ZALTRAP','FAULDLEUCO') THEN 'ONCOLOGIA'
WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN('HYQVIA','CUVITRU','GAMUNEX','OCTAGAM','HIZENTRA','TEGELINE','BLAUIMUNO','INTRATECT','FLEBOGAMMA','PENTAGLOBIN','IMUNOGLOBULIN','SANDOGLOBULINA','ENDOBULIN KIOVIG','EVUSHELD','CYRAMZA','IMJUDO','ENTYVIO','VEDOLIZUMABE','TREMFYA','DUPIXENT','TALTZ','SKYRIZI','COSENTYX','SECUQUINUMABE','STELARA','USTEQUINUMABE','BENLYSTA','ORENCIA','ABATACEPTE','CUPRIMINE','ACTEMRA','LEMTRADA','REBIF','AVONEX','TYSABRI','OCREVUS','KESIMPTA','OFATUMUMABE','REUQUINOL','XOLAIR','FASENRA','NUCALA','MEPOLIZUMABE','OFEV','NINTEDANIBE') THEN 'AUTOIMUNE'
ELSE 'NAO SE APLICA' END AS ESPECIALIDADE_PRIMARIA,

CASE WHEN DSC_PADRAO_SERVICO_MEDICAMENTO IN ('RIXIMYO','TRUXIMA','MABTHERA','RUXIENCE','VIVAXXIA','RITUXIMABE','YERVOY','IPILIMUMABE','LEUKINE','ZARZIO','FIPRIMA','FILGRASTIM','FILGRASTINE','GRANULOKINE','TEVAGRASTIM','LONQUEX','LIPEGFILGRASTIM','PELGRAZ','FULPHILA','NEULASTIM','PEGFILGRASTIM','HUMIRA','IDACIO','HYRIMOZ','AMGEVITA','XILBRILADA','ADALIMUMABE','CIMZIA','ENBREL','ERELZI','BRENZYS','ENBREL PFS','SIMPONI','AVSOLA','XILFYA','REMSIMA','REMICADE','INFLIXIMABE','BIO MANGUINHOS INFLIXIMABE','OLUMIANT','XELJANZ','RINVOQ') THEN 'AUTOIMUNE' 
ELSE 'NAO SE APLICA' END AS ESPECIALIDADE_SECUNDARIA
FROM TB_ESP_MEDICAMENTO_AJUSTAR
)
-------------------------------------------------------------
-- FIM das tabelas  especificas
-------------------------------------------------------------

-- CTE PARA COMPARAR OS RESULTADOS
, comparacao_classificacoes AS (
SELECT
    mcf.COD_TUSS_CONSOLIDADO__c,
    mcf.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
    mcf.INS_DSC_MEDICAMENTO_REF,
    
    mcf.INS_DSC_CLASSIFICACAO_MEDICAMENTO_NOVA AS nao_espec_CLASSIF_MEDICAMENTO,
    acf.DSC_CLASSIFICACAO_MEDICAMENTO_NOVA AS especifica_CLASSIF_MEDICAMENTO,
    
    mcf.INS_DSC_CLASSIFICACAO_VIA_ACESSO_NOVA AS nao_espec_VIA_ACESSO,
    acf.DSC_CLASSIFICACAO_VIA_ACESSO_NOVA AS especifica_VIA_ACESSO,
    
    mcf.INS_ESPECIALIDADE_PRIMARIA AS nao_espec_ESPEC_PRIMARIA,
    acf.ESPECIALIDADE_PRIMARIA AS especifica_ESPEC_PRIMARIA,
    
    mcf.INS_ESPECIALIDADE_SECUNDARIA AS nao_espec_ESPEC_SECUNDARIA,
    acf.ESPECIALIDADE_SECUNDARIA AS especifica_ESPEC_SECUNDARIA,
    
    -- Flags de divergência para cada campo
    CASE WHEN IFNULL(mcf.INS_DSC_CLASSIFICACAO_MEDICAMENTO_NOVA, '') != IFNULL(acf.DSC_CLASSIFICACAO_MEDICAMENTO_NOVA, '') THEN TRUE ELSE FALSE END AS DIV_CLASSIF_MEDICAMENTO,
    CASE WHEN IFNULL(mcf.INS_DSC_CLASSIFICACAO_VIA_ACESSO_NOVA, '') != IFNULL(acf.DSC_CLASSIFICACAO_VIA_ACESSO_NOVA, '') THEN TRUE ELSE FALSE END AS DIV_VIA_ACESSO,
    CASE WHEN IFNULL(mcf.INS_ESPECIALIDADE_PRIMARIA, '') != IFNULL(acf.ESPECIALIDADE_PRIMARIA, '') THEN TRUE ELSE FALSE END AS DIV_ESPEC_PRIMARIA,
    CASE WHEN IFNULL(mcf.INS_ESPECIALIDADE_SECUNDARIA, '') != IFNULL(acf.ESPECIALIDADE_SECUNDaria, '') THEN TRUE ELSE FALSE END AS DIV_ESPEC_SECUNDARIA,

    acf.COD_SERVICO_MATERIAL_MEDICAMENTO AS especifica_COD_SERVICO, -- Para verificar se houve match
    acf.DSC_PRINCIPIO_ATIVO_MEDICAMENTO AS especifica_PRINCIPIO_ATIVO,
    acf.DSC_PADRAO_SERVICO_MEDICAMENTO AS especifica_PADRAO_MEDICAMENTO

FROM nao_espec_classificacao_final mcf
LEFT JOIN especifica_classificacao_final acf 
    ON CAST(mcf.COD_TUSS_CONSOLIDADO__c AS STRING) = CAST(acf.COD_SERVICO_MATERIAL_MEDICAMENTO AS STRING)
    AND mcf.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO = acf.DSC_PRINCIPIO_ATIVO_MEDICAMENTO
   
)
-- CTE PARA DAR PREFERENCIA A TABELA DA ADRINA QUANDO O CODIGO TUSS For O Mesmo
, consolidacao_com_prioridade AS (
SELECT
    comp.COD_TUSS_CONSOLIDADO__c,
    comp.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
    comp.INS_DSC_MEDICAMENTO_REF,

    -- Classificação de Medicamento Final
    CASE 
        WHEN comp.especifica_COD_SERVICO IS NOT NULL AND comp.especifica_CLASSIF_MEDICAMENTO IS NOT NULL AND comp.DIV_CLASSIF_MEDICAMENTO = TRUE
        THEN comp.especifica_CLASSIF_MEDICAMENTO
        ELSE comp.nao_espec_CLASSIF_MEDICAMENTO
    END AS CLASSIFICACAO_MEDICAMENTO_CONSOLIDADA,

    -- Via de Acesso Final
    CASE 
        WHEN comp.especifica_COD_SERVICO IS NOT NULL AND comp.especifica_VIA_ACESSO IS NOT NULL AND comp.DIV_VIA_ACESSO = TRUE
        THEN comp.especifica_VIA_ACESSO
        ELSE comp.nao_espec_VIA_ACESSO
    END AS VIA_ACESSO_CONSOLIDADA,

    -- Especialidade Primária Final
    CASE 
        WHEN comp.especifica_COD_SERVICO IS NOT NULL AND comp.especifica_ESPEC_PRIMARIA IS NOT NULL AND comp.DIV_ESPEC_PRIMARIA = TRUE
        THEN comp.especifica_ESPEC_PRIMARIA
        ELSE comp.nao_espec_ESPEC_PRIMARIA
    END AS ESPEC_PRIMARIA_CONSOLIDADA,

    -- Especialidade Secundária Final
    CASE 
        WHEN comp.especifica_COD_SERVICO IS NOT NULL AND comp.especifica_ESPEC_SECUNDARIA IS NOT NULL AND comp.DIV_ESPEC_SECUNDARIA = TRUE
        THEN comp.especifica_ESPEC_SECUNDARIA
        ELSE comp.nao_espec_ESPEC_SECUNDARIA
    END AS ESPEC_SECUNDARIA_CONSOLIDADA,
    comp.nao_espec_CLASSIF_MEDICAMENTO,
    comp.especifica_CLASSIF_MEDICAMENTO,
    comp.DIV_CLASSIF_MEDICAMENTO,
    comp.nao_espec_VIA_ACESSO,
    comp.especifica_VIA_ACESSO,
    comp.DIV_VIA_ACESSO,
    comp.nao_espec_ESPEC_PRIMARIA,
    comp.especifica_ESPEC_PRIMARIA,
    comp.DIV_ESPEC_PRIMARIA,
    comp.nao_espec_ESPEC_SECUNDARIA,
    comp.especifica_ESPEC_SECUNDARIA,
    comp.DIV_ESPEC_SECUNDARIA,
    comp.especifica_COD_SERVICO 
FROM comparacao_classificacoes comp
),
-------------------------------------------------------------------------------------------------------------------------------------
tab_insumo_final AS (SELECT distinct
    COD_TUSS_CONSOLIDADO__c,
    INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
    --INS_DSC_MEDICAMENTO_REF,
    CLASSIFICACAO_MEDICAMENTO_CONSOLIDADA,
    --VIA_ACESSO_CONSOLIDADA,
    ESPEC_PRIMARIA_CONSOLIDADA,
    --ESPEC_SECUNDARIA_CONSOLIDADA,
    
    -- colunas da comp pra verificar mudançdas
    -- nao_espec_CLASSIF_MEDICAMENTO,
    -- especifica_CLASSIF_MEDICAMENTO,
    -- DIV_CLASSIF_MEDICAMENTO,
    -- nao_espec_VIA_ACESSO,
    -- especifica_VIA_ACESSO,
    -- DIV_VIA_ACESSO,
    -- nao_espec_ESPEC_PRIMARIA,
    -- especifica_ESPEC_PRIMARIA,
    -- DIV_ESPEC_PRIMARIA,
    -- nao_espec_ESPEC_SECUNDARIA,
    -- especifica_ESPEC_SECUNDARIA,
    -- DIV_ESPEC_SECUNDARIA,
    -- especifica_COD_SERVICO 
    
FROM consolidacao_com_prioridade
WHERE 1=1
--AND DIV_CLASSIF_MEDICAMENTO = TRUE 
--AND especifica_COD_SERVICO IS NULL and CLASSIFICACAO_MEDICAMENTO_CONSOLIDADA = 'REVER'
ORDER BY 
    COD_TUSS_CONSOLIDADO__c, 
    INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO),
-------------------------------------------------------------
--fim da comparação e agregação 
-------------------------------------------------------------
-- trazendo contas pagas 
SINISTRO AS (
  SELECT DISTINCT FLG_INTERNACAO,
  CAST(CONCAT(CAST(COD_DOCUMENTO_SINISTRO AS STRING),CAST(COD_COMPLEMENTO_SINISTRO AS STRING),
  CAST(COD_ORIGEM_PRESTADOR AS STRING),CAST(COD_SEQUENCIA_SINISTRO AS STRING),
  CAST(COD_ANEXO_ITEM_SERVICO_SINISTRO AS STRING),CAST(COD_ITEM_SERVICO_SINISTRO AS STRING)) AS STRING) AS COD_CHAVE_MAT_MED,
  FROM tab
  WHERE 1=1
)
------
,contas as(
SELECT 
COD_SERVICO_TUSS_CONSOLIDADO,
COD_SERVICO_MATERIAL_MEDICAMENTO as cod_servico,
COUNT(DISTINCT NUM_VPP) qnt_num_vpp,
SUM(VAL_PAGO_MATERIAL_MEDICAMENTO) VLR_PAGO_SERVICO , 
FROM
tab ITEM
LEFT JOIN SINISTRO
    ON CAST(CONCAT(CAST(COD_DOCUMENTO_SINISTRO AS STRING),CAST(COD_COMPLEMENTO_SINISTRO AS STRING),
    CAST(COD_ORIGEM_PRESTADOR AS STRING),CAST(COD_SEQUENCIA_SINISTRO AS STRING),
    CAST(COD_ANEXO_ITEM_SERVICO_SINISTRO AS STRING),CAST(COD_ITEM_SERVICO_SINISTRO AS STRING)) AS STRING) = SINISTRO.COD_CHAVE_MAT_MED

WHERE 1=1
AND DSC_SUB_GRUPO_SERVICO = 'MEDICAMENTO'
AND SINISTRO.FLG_INTERNACAO = 'N'
AND EXTRACT(YEAR FROM DAT_EXECUCAO_SINISTRO) = 2024
-- AND  COD_SERVICO_TUSS_CONSOLIDADO = '-2'
GROUP BY ALL
)
--select sum(VLR_PAGO_SERVICO) from contas 3,2 bi 
-------------
,tab_final as(
SELECT insumo.COD_TUSS_CONSOLIDADO__c,
insumo.INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
insumo.ESPEC_PRIMARIA_CONSOLIDADA ,
contas.qnt_num_vpp,
VLR_PAGO_SERVICO
FROM tab_insumo_final insumo 
inner JOIN contas 
ON lpad(cast(insumo.COD_TUSS_CONSOLIDADO__c as string),8,'0') = lpad(cast(contas.COD_SERVICO_TUSS_CONSOLIDADO as string),8,'0')
),
tb_final_ as (SELECT 
COD_TUSS_CONSOLIDADO__c,
INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
ESPEC_PRIMARIA_CONSOLIDADA ,
qnt_num_vpp,
VLR_PAGO_SERVICO --VAL_PAGO
FROM tab_final
group by all )
select COD_TUSS_CONSOLIDADO__c,INS_DSC_PRINCIPIO_ATIVO_NORMALIZADO,
       ESPEC_PRIMARIA_CONSOLIDADA,qnt_num_vpp,
       VLR_PAGO_SERVICO--sum(VLR_PAGO_SERVICO) --3,1 bi 
 from tb_final_ --where COD_TUSS_CONSOLIDADO__c = '90423380' 
